# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'SOGuidePage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
pod 'YLGIFImage'
  # Pods for Test

  target 'SOGuidePageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SOGuidePageUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
